project_id = "tbqqigqkbogibwumjyol"

[auth.email]
# Enable custom SMTP
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Custom email function configuration
[functions.send-auth-email]
verify_jwt = false

[functions.send-service-request-email]
verify_jwt = false

[functions.create-public-service-request]
verify_jwt = false

[functions.delete-users-and-clients]
verify_jwt = true

[functions.send-client-invite]
verify_jwt = true

[functions.complete-client-invite]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = true

[functions.create-user-account]
verify_jwt = true

[functions.mailjet-test-email]
verify_jwt = true

[functions.service-request-notify]
verify_jwt = true
