// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbqqigqkbogibwumjyol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRicXFpZ3FrYm9naWJ3dW1qeW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjE4OTAsImV4cCI6MjA2OTM5Nzg5MH0.PHRsaaVe9lHxcsqiv0K8-GOJlVEckACu_2Ng_2vfbY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});